In [1]:
import numpy as np
import matplotlib.pylab as plt
import ruptures as rpt
# creation of data
n, dim = 500, 3  # number of samples, dimension
n_bkps, sigma = 3, 5  # number of change points, noise standart deviation
signal, bkps = rpt.pw_constant(n, dim, n_bkps, noise_std=sigma)

In [10]:
[signal[x-1] for x in bkps]

[array([-1.9267853 , -0.7428434 ,  2.94910524]),
 array([  4.75094636, -15.11786488,   3.00133176]),
 array([-4.0644995 , -5.35170327,  4.14565938]),
 array([-15.29729964,  -2.46739454,  -2.17870728])]

In [11]:
c = rpt.costs.CostL1().fit(signal)
print(c.error(50, 150))

1381.3989158401002


In [12]:
c

In [13]:
print(c.sum_of_costs(bkps))
print(c.sum_of_costs([10, 100, 200, 250, n]))

6083.9815326802545
6684.169176730472
