In [2]:
import numpy as np
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from bokeh.models import LinearColorMapper, BasicTicker, ColorBar
from bokeh.palettes import Category10
output_notebook()

Loading BokehJS ...

In [6]:
Category10[10]

['#1f77b4',
 '#ff7f0e',
 '#2ca02c',
 '#d62728',
 '#9467bd',
 '#8c564b',
 '#e377c2',
 '#7f7f7f',
 '#bcbd22',
 '#17becf']

In [16]:
ys = np.random.multivariate_normal(np.zeros(3), np.eye(3))

In [17]:
ys

array([0.10165967, 1.48336598, 0.79460701])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
xs = np.linspace(0, 1, 2)

In [12]:
xs

array([0., 1.])

In [13]:
def plot_unit_gaussian_samples(D):
    p = figure(plot_width=800, plot_height=500, title='Samples from a unit {}D Gaussian'.format(D))

    xs = np.linspace(0, 1, D)
    for color in Category10[10]:
        ys = np.random.multivariate_normal(np.zeros(D), np.eye(D))
        p.line(xs, ys, line_width=1, color=color)
    return p

In [20]:
plot_unit_gaussian_samples(20)

Figure(id='1355', ...)

In [22]:
show(plot_unit_gaussian_samples(100))

In [49]:
N = 2
x = np.linspace(-2, 2, N)
y = np.linspace(-2, 2, N)

In [60]:
dx = np.expand_dims(x,1)-np.expand_dims(y,0)

In [61]:
dx

array([[ 0., -4.],
       [ 4.,  0.]])

In [62]:
def k(xs, ys, sigma=1, l=1):
    """Sqared Exponential kernel as above but designed to return the whole
    covariance matrix - i.e. the pairwise covariance of the vectors xs & ys.
    Also with two parameters which are discussed at the end."""

    # Pairwise difference matrix.
    dx = np.expand_dims(xs, 1) - np.expand_dims(ys, 0)
    return (sigma ** 2) * np.exp(-((dx / l) ** 2) / 2)

def m(x):
    """The mean function. As discussed, we can let the mean always be zero."""
    return np.zeros_like(x)

In [63]:
x = np.linspace(-5,5,100)

In [64]:
m(x)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
k(x,x)

array([[1.00000000e+00, 9.94911470e-01, 9.79800714e-01, ...,
        1.42487329e-21, 5.26916305e-22, 1.92874985e-22],
       [9.94911470e-01, 1.00000000e+00, 9.94911470e-01, ...,
        3.81399159e-21, 1.42487329e-21, 5.26916305e-22],
       [9.79800714e-01, 9.94911470e-01, 1.00000000e+00, ...,
        1.01053670e-20, 3.81399159e-21, 1.42487329e-21],
       ...,
       [1.42487329e-21, 3.81399159e-21, 1.01053670e-20, ...,
        1.00000000e+00, 9.94911470e-01, 9.79800714e-01],
       [5.26916305e-22, 1.42487329e-21, 3.81399159e-21, ...,
        9.94911470e-01, 1.00000000e+00, 9.94911470e-01],
       [1.92874985e-22, 5.26916305e-22, 1.42487329e-21, ...,
        9.79800714e-01, 9.94911470e-01, 1.00000000e+00]])

In [66]:
stds = np.sqrt(Sigma_s.diagonal())

NameError: name 'Sigma_s' is not defined

In [67]:
x_s = np.linspace(-8, 7, 80)

In [68]:
np.flip(x_s, 0)

array([ 7.        ,  6.81012658,  6.62025316,  6.43037975,  6.24050633,
        6.05063291,  5.86075949,  5.67088608,  5.48101266,  5.29113924,
        5.10126582,  4.91139241,  4.72151899,  4.53164557,  4.34177215,
        4.15189873,  3.96202532,  3.7721519 ,  3.58227848,  3.39240506,
        3.20253165,  3.01265823,  2.82278481,  2.63291139,  2.44303797,
        2.25316456,  2.06329114,  1.87341772,  1.6835443 ,  1.49367089,
        1.30379747,  1.11392405,  0.92405063,  0.73417722,  0.5443038 ,
        0.35443038,  0.16455696, -0.02531646, -0.21518987, -0.40506329,
       -0.59493671, -0.78481013, -0.97468354, -1.16455696, -1.35443038,
       -1.5443038 , -1.73417722, -1.92405063, -2.11392405, -2.30379747,
       -2.49367089, -2.6835443 , -2.87341772, -3.06329114, -3.25316456,
       -3.44303797, -3.63291139, -3.82278481, -4.01265823, -4.20253165,
       -4.39240506, -4.58227848, -4.7721519 , -4.96202532, -5.15189873,
       -5.34177215, -5.53164557, -5.72151899, -5.91139241, -6.10

In [69]:
x_s

array([-8.        , -7.81012658, -7.62025316, -7.43037975, -7.24050633,
       -7.05063291, -6.86075949, -6.67088608, -6.48101266, -6.29113924,
       -6.10126582, -5.91139241, -5.72151899, -5.53164557, -5.34177215,
       -5.15189873, -4.96202532, -4.7721519 , -4.58227848, -4.39240506,
       -4.20253165, -4.01265823, -3.82278481, -3.63291139, -3.44303797,
       -3.25316456, -3.06329114, -2.87341772, -2.6835443 , -2.49367089,
       -2.30379747, -2.11392405, -1.92405063, -1.73417722, -1.5443038 ,
       -1.35443038, -1.16455696, -0.97468354, -0.78481013, -0.59493671,
       -0.40506329, -0.21518987, -0.02531646,  0.16455696,  0.35443038,
        0.5443038 ,  0.73417722,  0.92405063,  1.11392405,  1.30379747,
        1.49367089,  1.6835443 ,  1.87341772,  2.06329114,  2.25316456,
        2.44303797,  2.63291139,  2.82278481,  3.01265823,  3.20253165,
        3.39240506,  3.58227848,  3.7721519 ,  3.96202532,  4.15189873,
        4.34177215,  4.53164557,  4.72151899,  4.91139241,  5.10

In [70]:
np.concatenate((x_s, np.flip(x_s, 0)))

array([-8.        , -7.81012658, -7.62025316, -7.43037975, -7.24050633,
       -7.05063291, -6.86075949, -6.67088608, -6.48101266, -6.29113924,
       -6.10126582, -5.91139241, -5.72151899, -5.53164557, -5.34177215,
       -5.15189873, -4.96202532, -4.7721519 , -4.58227848, -4.39240506,
       -4.20253165, -4.01265823, -3.82278481, -3.63291139, -3.44303797,
       -3.25316456, -3.06329114, -2.87341772, -2.6835443 , -2.49367089,
       -2.30379747, -2.11392405, -1.92405063, -1.73417722, -1.5443038 ,
       -1.35443038, -1.16455696, -0.97468354, -0.78481013, -0.59493671,
       -0.40506329, -0.21518987, -0.02531646,  0.16455696,  0.35443038,
        0.5443038 ,  0.73417722,  0.92405063,  1.11392405,  1.30379747,
        1.49367089,  1.6835443 ,  1.87341772,  2.06329114,  2.25316456,
        2.44303797,  2.63291139,  2.82278481,  3.01265823,  3.20253165,
        3.39240506,  3.58227848,  3.7721519 ,  3.96202532,  4.15189873,
        4.34177215,  4.53164557,  4.72151899,  4.91139241,  5.10

In [71]:
coefs = [6, -2.5, -2.4, -0.1, 0.2, 0.03]

def f(x):
    total = 0
    for exp, coef in enumerate(coefs):
        total += coef * (x ** exp)
    return total

In [74]:
[i for i in enumerate(coefs)]

[(0, 6), (1, -2.5), (2, -2.4), (3, -0.1), (4, 0.2), (5, 0.03)]

In [75]:
x_obs = np.array([-4, -1.5, 0, 1.5, 2.5, 2.7])
y_obs = f(x_obs)

x_s = np.linspace(-8, 7, 80)

In [76]:
y_obs

array([ 4.48     ,  5.4721875,  6.       , -2.2471875, -6.0703125,
       -5.2808079])

In [79]:
p = figure(plot_width = 800,plot_height = 400,x_axis_label = 'x',y_axis_label = 'f(x)',title = 'kill me')
p.line(x_obs,y_obs,line_width = 2)
show(p)

In [80]:
K = k(x_obs, x_obs)
K_s = k(x_obs, x_s)
K_ss = k(x_s, x_s)

K_sTKinv = np.matmul(K_s.T, np.linalg.pinv(K))

mu_s = m(x_s) + np.matmul(K_sTKinv, y_obs - m(x_obs))
Sigma_s = K_ss - np.matmul(K_sTKinv, K_s)

In [88]:
Sigma_s[79]

array([ 4.34986052e-10,  9.13015936e-10,  1.84848852e-09,  3.60982367e-09,
        6.79952767e-09,  1.23533084e-08,  2.16461527e-08,  3.65797444e-08,
        5.96093287e-08,  9.36532047e-08,  1.41820442e-07,  2.06898493e-07,
        2.90565844e-07,  3.92333651e-07,  5.08265395e-07,  6.29561374e-07,
        7.41115274e-07,  8.20157221e-07,  8.35118118e-07,  7.44930464e-07,
        4.99168384e-07,  3.97357668e-08, -6.94830625e-07, -1.76113726e-06,
       -3.19762354e-06, -5.00579530e-06, -7.12725178e-06, -9.42011785e-06,
       -1.16411648e-05, -1.34420970e-05, -1.43891829e-05, -1.40136371e-05,
       -1.18952638e-05, -7.77389002e-06, -1.67293553e-06,  5.99100563e-06,
        1.43466806e-05,  2.20909847e-05,  2.76250507e-05,  2.93137235e-05,
        2.58479689e-05,  1.66514713e-05,  2.23552165e-06, -1.56164228e-05,
       -3.39465148e-05, -4.90677899e-05, -5.73349102e-05, -5.61070209e-05,
       -4.46664324e-05, -2.48031200e-05, -8.03584167e-07,  2.13004969e-05,
        3.51981113e-05,  

In [95]:
p = figure(plot_width=800, plot_height=600, y_range=(-7, 8))

y_true = f(x_s)
p.line(x_s, y_true, line_width=3, color='black', alpha=0.4, line_dash='dashed', legend='True f(x)')

p.cross(x_obs, y_obs, size=20, legend='Training data')

stds = np.sqrt(Sigma_s.diagonal())
err_xs = np.concatenate((x_s,np.flip(x_s,0)))
err_ys = np.concatenate((mu_s + 2 * stds,np.flip(mu_s - 2 * stds,0)))
p.patch(err_xs, err_ys, alpha=0.2, line_width=0, color='grey', legend='Uncertainty')

for color in Category10[3]:
    y_s = np.random.multivariate_normal(mu_s, Sigma_s)
    p.line(x_s, y_s, line_width=1, color=color)
    
p.line(x_s, mu_s, line_width=3, color='blue', alpha=0.4, legend='Mean')
show(p)

In [3]:
p = figure(plot_width = 800, plot_height = 600 , y_range = (-7,8))

In [6]:
coefs = [6, -2.5, -2.4, -0.1, 0.2, 0.03]

def f(x):
    total = 0
    for exp, coef in enumerate(coefs):
        total += coef * (x ** exp)
    return total

In [8]:
x = np.array([-8.0,-2,0,1,2,6])
f(x)

array([-240.24,    4.44,    6.  ,    1.23,   -5.24,  375.48])

In [12]:
p.cross(x,f(x),size=30)
show(p)